-- query 1
SELECT CUSTOMER.CUS_LNAME, INVOICE.INV_NUMBER, INVOICE.INV_DATE, INVOICE.INV_TOTAL
	FROM CUSTOMER
	INNER JOIN INVOICE ON CUSTOMER.CUS_CODE = INVOICE.CUS_CODE;


-- query 2
SELECT DISTINCT CUSTOMER.CUS_LNAME, INVOICE.INV_NUMBER, INVOICE.INV_DATE, INVOICE.INV_TOTAL
	FROM ((((CUSTOMER
	INNER JOIN INVOICE ON CUSTOMER.CUS_CODE = INVOICE.CUS_CODE) 
	INNER JOIN LINE ON LINE.INV_NUMBER = INVOICE.INV_NUMBER) 
	INNER JOIN PRODUCT ON LINE.P_CODE = PRODUCT.P_CODE) 
	INNER JOIN VENDOR ON PRODUCT.V_CODE = VENDOR.V_CODE);


-- query 3
SELECT CUSTOMER.CUS_LNAME, INVOICE.INV_NUMBER, INVOICE.INV_DATE, PRODUCT.P_DESCRIPT
	FROM (((CUSTOMER
	INNER JOIN INVOICE ON CUSTOMER.CUS_CODE = INVOICE.CUS_CODE) 
	INNER JOIN LINE ON LINE.INV_NUMBER = INVOICE.INV_NUMBER) 
	INNER JOIN PRODUCT ON LINE.P_CODE = PRODUCT.P_CODE);

-- query 4
SELECT PRODUCT.P_DESCRIPT, INVOICE.INV_NUMBER, INVOICE.INV_DATE
	FROM ((INVOICE 
	INNER JOIN LINE ON LINE.INV_NUMBER = INVOICE.INV_NUMBER) 
	INNER JOIN PRODUCT ON LINE.P_CODE = PRODUCT.P_CODE);