

--query 1
SELECT COUNTRY, COUNT(CUSTID) AS CUSTOMERS
	FROM CUSTOMER
	GROUP BY COUNTRY
	HAVING CUSTOMERS > 10;

--query 2
SELECT COUNTRY, COUNT(CUSTID) AS CUSTOMERS
	FROM CUSTOMER
	WHERE COUNTRY != 'USA'
	GROUP BY COUNTRY
	HAVING CUSTOMERS >= 9;	

--query 3
SELECT CUSTID, AVG(TOTALAMOUNT) AS Average
	FROM ORDERS
	GROUP BY(CUSTID)
	HAVING Average > 1000 
	AND Average < 1200;

--query 4
SELECT COUNT(CUSTID) AS CUSTOMERS, CITY, COUNTRY
	FROM CUSTOMER
	GROUP BY (COUNTRY), (CITY);


--query 6
SELECT FIRSTNAME, ORDERS.CUSTID, COUNT(ORDID)
	FROM CUSTOMER, ORDERS
	WHERE CUSTOMER.CUSTID = ORDERS.CUSTID
	GROUP BY ORDERS.CUSTID;



--query 7
SELECT ORDERS.CUSTID, COUNT(ORDID) orderer
	FROM  CUSTOMER
	INNER JOIN ORDERS ON ORDERS.CUSTID = CUSTOMER.CUSTID
	GROUP BY ORDERS.CUSTID
	HAVING orderer = ( SELECT MAX(output.amount)
						FROM 
						(SELECT COUNT(ORDERS.ORDID) amount, ORDERS.CUSTID
							FROM  CUSTOMER
							INNER JOIN ORDERS ON ORDERS.CUSTID = CUSTOMER.CUSTID
							GROUP BY ORDERS.CUSTID) output);


-- query 8
SELECT ORDERS.CUSTID, COUNT(ORDID) orderer
	FROM  CUSTOMER
	INNER JOIN ORDERS ON ORDERS.CUSTID = CUSTOMER.CUSTID
	GROUP BY ORDERS.CUSTID
	HAVING orderer = ( SELECT MIN(output.amount)
						FROM 
						(SELECT COUNT(ORDERS.ORDID) amount, ORDERS.CUSTID
							FROM  CUSTOMER
							INNER JOIN ORDERS ON ORDERS.CUSTID = CUSTOMER.CUSTID
							GROUP BY ORDERS.CUSTID) output);


--query 9
SELECT ORDERDATE, COUNT(TOTALAMOUNT) sales 
	FROM  ORDERS
	GROUP BY ORDERDATE
	HAVING sales = ( SELECT MAX(output.amount)
						FROM 
						(SELECT ORDERDATE, COUNT(TOTALAMOUNT) amount
							FROM  ORDERS
							GROUP BY ORDERDATE) output);