
--query 1
SELECT DEPT_ID, COUNT(EMP_ID) AS EMPLOYEES, SUM(SALARY) AS TOTALSALARY
	FROM EMPLOYEE
	GROUP BY DEPT_ID;

--query 2
SELECT COUNT(EMP_ID) AS EMPLOYEES, DEPT_ID  AS DEPARTMENT, MANAGER_ID AS MANAGER
	FROM EMPLOYEE
	GROUP BY DEPARTMENT, MANAGER; 


--query 3
SELECT AVG(SALARY) as Average_Salary, JOB_ID
	FROM EMPLOYEE
	GROUP BY JOB_ID;


--query 4
SELECT COUNT(EMP_ID) EMPLOYEES, MANAGER_ID  MANAGER
	FROM EMPLOYEE
	GROUP BY MANAGER_ID
	HAVING EMPLOYEES = (SELECT MAX(emp) FROM (SELECT COUNT(EMP_ID) emp , MANAGER_ID FROM EMPLOYEE GROUP BY MANAGER_ID) AS data);


--query 5
SELECT COUNT(EMP_ID), AVG(SALARY), DEPT_ID  AS DEPARTMENT, JOB_ID AS DESIGNATION
	FROM EMPLOYEE
	GROUP BY DEPARTMENT, DESIGNATION; 


--query 6
SELECT COUNT(EMP_ID) AS EMPLOYEES, MANAGER_ID AS MANAGER
	FROM EMPLOYEE
	GROUP BY MANAGER
	ORDER BY MANAGER; 


--query 7
SELECT COUNT(FINAL.MANAGER), FINAL.DEPARTMENT
	FROM (SELECT  MANAGER_ID MANAGER, COUNT(EMP_ID), DEPT_ID  DEPARTMENT
		FROM EMPLOYEE
		GROUP BY MANAGER, DEPARTMENT) FINAL
	GROUP BY FINAL.DEPARTMENT;



--query 8
SELECT COUNT(EMP_ID) EMPLOYEES, DEPT_ID DEPARTMENT
	FROM EMPLOYEE
	GROUP BY DEPARTMENT
	HAVING EMPLOYEES > 3;



--query 9
SELECT COUNT(EMP_ID) EMPLOYEES, DEPT_ID  DEPARTMENT
	FROM EMPLOYEE
	GROUP BY DEPT_ID
	HAVING EMPLOYEES = (SELECT MAX(data.emp) FROM (SELECT COUNT(EMP_ID) emp , DEPT_ID FROM EMPLOYEE GROUP BY DEPT_ID) AS data);



--query 10
SELECT COUNT(EMP_ID) EMPLOYEES, DEPT_ID  DEPARTMENT
	FROM EMPLOYEE
	GROUP BY DEPT_ID
	HAVING EMPLOYEES = (SELECT MIN(data.emp) FROM (SELECT COUNT(EMP_ID) emp , DEPT_ID FROM EMPLOYEE GROUP BY DEPT_ID) AS data);